name: Java CI with Maven
on: [push]

# This section specifies the jobs/steps to be executed in the workflow
jobs:
  # This workflow only has a single job
  build:
    runs-on: ubuntu-latest
    # Here are the steps to be executed by the machine running this job
    steps:
      - uses: actions/checkout@v3
        # Setup Java
      - name: Setup JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  8.0.332+9
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install --file e-shop-manager/pom.xml
      - name: Test(JaCoCo)
        run: mvn test jacoco:report --file e-shop-manager/pom.xml
